apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uveggb3hw-python 
  janus-idp.io/tekton: uveggb3hw-python
  backstage.io/kubernetes-id: uveggb3hw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uveggb3hw-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  